from selenium import webdriver
import selenium
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select          # Select class is imported when dealing with select in html
driver = webdriver.Chrome(executable_path="C:\seleniumdrivers\chromedriver.exe")
driver.get("http://automationpractice.com/")
driver.implicitly_wait(5)
driver.find_element_by_xpath("//*[@id='header']/div[2]/div/div/nav/div[1]/a").click()
email_ele=driver.find_element_by_name("email_create")
print(email_ele.is_displayed())
print(email_ele.is_enabled())
email_ele.send_keys("ravyaa@gmail.com")
driver.find_element_by_xpath("//*[@id='SubmitCreate']/span").click()
radiobutton_mrs=driver.find_element_by_id("uniform-id_gender2")
radiobutton_mrs.click()
driver.find_element_by_id("customer_firstname").send_keys("vennela")
driver.find_element_by_id("customer_lastname").send_keys("oneu")
driver.find_element_by_id("email").clear()
driver.find_element_by_id("email").send_keys("ravya@gmail.com")
driver.find_element_by_id("passwd").send_keys("5525252")
ddp=driver.find_element_by_id("days")
ddp1=Select(ddp)
ddp1.select_by_value("21")       #value is assigned based on the page source
mondp=driver.find_element_by_id("months")
mondp1=Select(mondp)
mondp1.select_by_value("12")
yrdp=driver.find_element_by_id("years")
yrdp1=Select(yrdp)
yrdp1.select_by_value("1990")
driver.find_element_by_xpath("//*[@id='newsletter']").click()
driver.find_element_by_xpath("//*[@id='optin']").click()
driver.find_element_by_xpath("//*[@id='firstname']").send_keys("vennela")
driver.find_element_by_id("lastname").send_keys("oneu")
driver.find_element_by_id("company").send_keys("lagev")
driver.find_element_by_id("address1").send_keys("2222 heaven ln")
driver.find_element_by_id("city").send_keys("madras")
dpst=driver.find_element_by_id("id_state")
dpst1=Select(dpst)
dpst1.select_by_value("37")
driver.find_element_by_id("postcode").send_keys(97701)
co=driver.find_element_by_id("id_country")
co1=Select(co)
co1.select_by_value("21")
driver.find_element_by_name("phone").send_keys(5414104100)
driver.find_element_by_id("phone_mobile").send_keys(5475896253)
driver.find_element_by_name("alias").send_keys("210 bend, or")


driver.find_element_by_xpath("//*[@id='submitAccount']/span").click()
time.sleep(10)
driver.close()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    